export const dom = {
  homeWrap: document.getElementById("homeWrap"),
  resultsWrap: document.getElementById("resultsWrap"),
  homeInput: document.getElementById("homeInput"),
  resultsInput: document.getElementById("resultsInput"),
  homeSuggest: document.getElementById("homeSuggest"),
  resultsSuggest: document.getElementById("resultsSuggest"),
  homeClear: document.getElementById("homeClear"),
  resultsClear: document.getElementById("resultsClear"),
  homeSearchBar: document.getElementById("homeSearchBar"),
  resultsSearchBar: document.getElementById("resultsSearchBar"),
  trendingChips: document.getElementById("trendingChips"),
  tabsRow: document.getElementById("tabsRow"),
  resultsList: document.getElementById("resultsList"),
  resultStats: document.getElementById("resultStats"),
  knowledgePanel: document.getElementById("knowledgePanel"),
  pagination: document.getElementById("pagination"),
  themeToggle: document.getElementById("themeToggle"),
  feelingLuckyBtn: document.getElementById("feelingLuckyBtn"),
  searchBtn: document.getElementById("searchBtn"),
  logos: document.querySelectorAll(".logo"),
};
