export const KNOWLEDGE = {
  "css grid": {
    title: "CSS Grid",
    category: "Layout module",
    icon: "▦",
    desc: "A two-dimensional CSS layout system that lets you arrange elements into rows and columns without extra markup or floats.",
    facts: [
      ["Introduced", "2017 (CSS3)"],
      ["Browser support", "97%+ global"],
      ["Related", "Flexbox, Subgrid"],
      ["Spec status", "W3C Candidate Rec"],
    ],
    links: ["grid-template", "fr unit", "subgrid"],
  },
  scysearch: {
    title: "ScySearch",
    category: "Developer search engine",
    icon: "S",
    desc: "A meta-search tool that aggregates Stack Overflow, GitHub, MDN, Hacker News, Reddit, and Dev.to into one ranked result set, part of the Scybud studio.",
    facts: [
      ["Built by", "Abdulroqib"],
      ["Sources", "Stack Overflow, GitHub, MDN, HN, Reddit, Dev.to"],
      ["Stack", "Vanilla JS + Supabase Edge Functions"],
    ],
    links: ["scybud.com", "GitHub"],
  },
  scybud: {
    title: "Scybud",
    category: "Software discovery platform",
    icon: "S",
    desc: "A curated platform for discovering, launching, and managing indie software products, where every submission is reviewed before it goes live. Also the home for every first-party Scybud product.",
    facts: [
      ["Founded by", "Abdulroqib"],
      ["Based in", "Bremen, Germany"],
      ["Stack", "Vanilla HTML/CSS/JS + Supabase"],
      ["Design", "Dark mode first"],
    ],
    links: ["scybud.com", "ui.scybud.com", "Scyflix"],
  },
  loghue: {
    title: "LogHue",
    category: "Productivity SaaS",
    icon: "L",
    desc: "Solo-first task, note, and workspace management, with team features layered on top rather than the default. Search-first dashboard, a global command palette, and a calendar view of task deadlines.",
    facts: [
      ["Launched", "2026"],
      ["Stack", "Vanilla JS + Supabase"],
      ["Accent color", "Blue #3b82f6"],
      ["Pricing", "Free + one paid tier"],
    ],
    links: ["loghue.com", "app.loghue.com", "docs.loghue.com"],
  },
  zefeed: {
    title: "ZeFeed",
    category: "Tech news reader",
    icon: "Z",
    desc: "A minimal way to keep up with tech: quick news summaries, an article explore feed, and flashcard-style tech history facts, without needing to read a full article to stay current.",
    facts: [
      ["Launched", "2026"],
      ["Stack", "Vanilla JS + Supabase"],
      ["Pages", "Home, Explore, History"],
      ["Hosted at", "zefeed.vercel.app"],
    ],
    links: ["zefeed.vercel.app"],
  },
  propdek: {
    title: "PropDek",
    category: "Property management platform",
    icon: "P",
    desc: "Built for agents to manage their clients and the assets those clients own, tracking tenants within each property. Sale and rent listings can go to the PropDek Marketplace.",
    facts: [
      ["Launched", "2026"],
      ["Focus", "Nigerian real estate market"],
      ["Stack", "Vanilla JS + Supabase"],
      ["Hosted at", "propdek.scybud.com"],
    ],
    links: ["propdek.scybud.com"],
  },
  canvart: {
    title: "CanvArt",
    category: "Art sharing platform",
    icon: "C",
    desc: "A dark-mode space to share art of any kind, drawings, paintings, photos, built to welcome novices rather than cater only to professionals like most art platforms do.",
    facts: [
      ["Launched", "2026"],
      ["Stack", "Vanilla JS + Supabase"],
      ["Design", "Dark mode"],
      ["Hosted at", "canvart.scybud.com"],
    ],
    links: ["canvart.scybud.com"],
  },
  dakat: {
    title: "DakAt",
    category: "Browser extension",
    icon: "D",
    desc: "Forces a readable dark theme onto any site that doesn't ship one natively, born out of frustration with light-mode-only tools like itslearning and Pinterest.",
    facts: [
      ["Launched", "2026"],
      ["Type", "Browser extension"],
      ["Hosted at", "dakat.scybud.com"],
    ],
    links: ["dakat.scybud.com"],
  },
  trytasty: {
    title: "TryTasty",
    category: "Recipe platform",
    icon: "T",
    desc: "Simple, easy-to-make recipes built mostly from basic ingredients, started as an experiment in low-friction cooking content.",
    facts: [
      ["Launched", "2025"],
      ["Hosted at", "trytasty.scybud.com"],
    ],
    links: ["trytasty.scybud.com"],
  },
  rushsite: {
    title: "Rushsite",
    category: "Portfolio builder",
    icon: "R",
    desc: "Build a portfolio from templates, with data persisted across templates so switching designs doesn't mean re-entering everything.",
    facts: [
      ["Launched", "2025"],
      ["Hosted at", "rushsite.scybud.com"],
    ],
    links: ["rushsite.scybud.com"],
  },
  scyflix: {
    title: "Scyflix",
    category: "Build-in-public brand",
    icon: "S",
    desc: "Progress logs and behind-the-scenes posts documenting the day-to-day of building the Scybud studio. Predates Scybud, the name Scybud was derived from it.",
    facts: [["Hosted at", "scyflix.github.io"]],
    links: ["scyflix.github.io"],
  },
  "scybud ui": {
    title: "Scybud UI",
    category: "Design system",
    icon: "U",
    desc: "A shared, open-source component library of CSS custom properties and components used across every Scybud product, built to stop repeating the same styles across projects.",
    facts: [
      ["Released", "2026"],
      ["Open source", "Yes"],
      ["Hosted at", "ui.scybud.com"],
    ],
    links: ["ui.scybud.com"],
  },
};

export function getKnowledgePanel(query) {
  return KNOWLEDGE[query.toLowerCase().trim()] || null;
}
